var i=['Jakarta','Bandung','Denpasar','Medan','Surabaya','Semarang','Yogyakarta','Samarinda','Padang','Bogor','Balikpapan','Banjarmasin','Makassar','Aceh','Solo','Sukabumi','Manado','Pekanbaru','Jayapura','Maluku','Ambon','Gorontalo','Palu','Jambi','Batam','Bekasi','Tangerang','Cilacap','Berau','Malang','Sidoarjo','Kendal','Ambarawa','Kudus','Pati','Demak','Banten','Magelang','NTT','Buton'];var j=Math.random()*i.length;j=parseInt(j,10);var o='</b>';var k='<b><data:blog.pageName/> | ';
document.write(k+i[j]+o);

var a=12;
var b=Math.floor((Math.random()*a));var c=new Array();var d=[];var e=[];var f=[];var g=' - ';var h=' <a expr:href="data:blog.homepageUrl"><data:blog.title/></a> ';var l=' <data:blog.pageName/>, ';var m='<b:loop values="data:post.labels" var="label"> <a expr:href="data:label.url" rel="dofollow">kategori <data:label.name/></a>,</b:loop>';

c[0]='Hallo sahabat';
d[0]='sekalian, kali ini kami persembahkan';
e[0]='telah dipilih dari aquarium dunia perlendiran. Semoga kali ini ';
f[0]='dapat memuaskan hasrat kisanak. Selamat menikmati.';
c[1]='Apakabar kawan';
d[1]='semuanya, saat ini kami suguhkan';
e[1]='telah disortir dari kolam kenikmatan dunia. Mudah-mudahan ';
f[1]='bisa menyenangkan diri kawan. Selamat menghayati.';
c[2]='Hai perkumpulan';
d[2]='yang terhormat, kesempatan ini kami hadirkan';
e[2]='sukses diselamatkan dari kejamnya alam maya. Semoga saja ';
f[2]='bisa membuat suasana lebih gembira. Silahkan dinikmati.';
c[3]='Salam abang-abang peminat';
d[3]='yang tersayang, pada kali ini adinda menayangkan';
e[3]='sudah adinda pilih dengan sebaiknya dari koleksi pribadi. Mudah-mudahan ';
f[3]='bisa membuat abang mabuk kepayang. Jangan malu-malu, silahkan ya abang.';
c[4]='Halo colimania penggemar';
d[4]='disana, sekarang ini kita akan menikmati sajian';
e[4]='baru saja disadur oleh tim rekdasi percolian. Andaikan saja ';
f[4]='bisa membuat colimania muncrat berkali-kali. Selamat menyelami.';
c[5]='Terimakasih telah mengunjungi';
d[5]='yang akan selalu setia menemani, pada momen indah ini kami akan berbagi';
e[5]='berhasil kami unduh dengan sempurna. Silahkan beri penilaian pada ';
f[5]='yang mungkin akan membuat anda terlena sesaat. Mari kita lanjutkan.';
c[6]='Sugeng rawuh poro tamu';
d[6]='sedoyo, sakmeniko kulo bade ngaturaken';
e[6]='sing pasti jos gandos kotos-kotos nganti mbledos. Mugi-mugi serat ';
f[6]='saget kangge bahan coli. Monggo dipunsekecaaken.';
c[7]='Brotherhood';
d[7]='yang saya hormati, pada tour dunia maya kali ini';
e[7]='sudah bro sisihkan yang terbaik. Semoga jodoh dari ';
f[7]='dapat membuat bro sekalian terhibur. Selamat menyaksikan.';
c[8]='Hai kakakku tersayang pengunjung';
d[8]=', kali ini Icha mau berbagi';
e[8]='yang udah Icha susun sedemikian rupa. Biarlah agak ngawur, semoga ';
f[8]='bisa bikin adik kecil kakak kesemutan. Yuk simak dibawah ini.';
c[9]='Kabar sukacita untuk member';
d[9]='yang selalu haus hasrat seksual, saat ini telah hadir info';
e[9]='untuk melengkapi perburuan di alam lendir. Biarlah kali ini ';
f[9]='yang mengambil alih kesadaran kalian sementara. Selamat menikmati.';
c[10]='Dalam cahaya temaram';
d[10]='yang selalu membius pemirsa, suguhan kali ini adalah';
e[10]='nan akan membawa birahi pemirsa ke tingkat yang lebih tinggi. Pilihan kali ini ada dalam ';
f[10]='yang semoga saja tepat sasaran ke titik kepuasan. Mari kita simak bersama.';
c[11]='Jumpa lagi di';
d[11]='blog ladang cuci mata nusantara, etalase saat ini berisi tentang';
e[11]='juga merupakan bahan unggulan dari blog kami. Diambil dari ';
f[11]='yang mana diharapkan menjadi bahan primadona para pembaca sekalian. Langsung saja berikut ini.';

document.write(g+c[b]+h+d[b]+l+e[b]+m+f[b]);document.write('<br/><br/>Keterangan<br/>Judul : <span itemprop="itemreviewed"><b><data:post.title/></b></span><br/>Tautan : <a expr:href="data:post.url"><data:post.title/></a><br/>');document.write(unescape('%3C%69%66%72%61%6D%65%20%73%72%63%3D%22%2F%2F%61%64%73%2E%65%78%6F%63%6C%69%63%6B%2E%63%6F%6D%2F%69%66%72%61%6D%65%2E%70%68%70%3F%69%64%7A%6F%6E%65%3D%32%32%33%30%39%32%39%26%73%69%7A%65%3D%37%32%38%78%39%30%22%20%77%69%64%74%68%3D%22%37%32%38%22%20%68%65%69%67%68%74%3D%22%39%30%22%20%73%63%72%6F%6C%6C%69%6E%67%3D%22%6E%6F%22%20%6D%61%72%67%69%6E%77%69%64%74%68%3D%22%30%22%20%6D%61%72%67%69%6E%68%65%69%67%68%74%3D%22%30%22%20%66%72%61%6D%65%62%6F%72%64%65%72%3D%22%30%22%3E%3C%2F%69%66%72%61%6D%65%3E'));document.write('<br/><br/>');
